Settings:
  Prefix: '&7[&4Crazy &bAuctions&7]: ' #Prefix of when you get Crazy Auctions Messages.
  GUIName: '&4Crazy &bAuctions&8' #Name of the Main GUI.
  Players-Current-Items: '&8Seus itens atuais' #The Name of the Player Current Items GUI.
  Cancelled/Expired-Items: '&8Cancelado/Expirados' #Name of the Cancelled/Expired GUI.
  Buying-Item: '&8Quer mesmo comprar este item?' #Name of the Buying GUI.
  Bidding-On-Item: '&8Você está penhorando este item..' #Name of the Bidding GUI.
  Categories: '&8Categorias' #Name of the Category GUI.
  Sell-Time: 1d #The time that each item will sell for.
  Bid-Time: 2m 30s #Time for each item that is biddable.
  Full-Expire-Time: 5d #The full time the item is in the crazy auctions.
  Bid-Winner-Time: 10d #The time the winner of a bid has to claim there prize.
  Minimum-Sell-Price: 0.005 #Minimum amount you can sell a item for.
  Max-Beginning-Sell-Price: 1000000 #Max amount you can sell a item for.
  Minimum-Bid-Price: 0.01 #Minimum starting bid.
  Max-Beginning-Bid-Price: 1000000 #Maximum starting bid.
  Allow-Damaged-Items: False #Allow items that have been damaged.
  Category-Page-Opens-First: False #If set to true the categories page will open when they do /CA.
  Sounds:
    Toggle: False #Disable the clicking sound.
    Sound: 'CLICK' #Make sure if you use 1.8 or lower you use the 1.8 sound and 1.9 and up use 1.9 sounds. The default sound is 1.8.
    #1.8 sounds are found here: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
    #1.9 sounds are found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  GUISettings: #Settings for things in the gui.
    SellingItemLore: #The lore on items that are being sold.
      - '&7-------------------------'
      - '&aClique aqui para comprar.'
      - ''
      - '&9Preço: &e$%Price%'
      - '&9Vendedor: &e%Seller%'
      - '&7-------------------------'
    CurrentLore: #Lore on items that are in your current items GUI.
      - '&7-------------------------'
      - '&aClique aqui e cancele.'
      - ''
      - '&9Preço: &e$%Price%'
      - '&9Expirado em: &e%Time%'
      - '&7-------------------------'
    Cancelled/ExpiredLore: #Lore on items that are in your cancelled/expired GUI.
      - '&7-------------------------'
      - '&aClique para pegar de volta.'
      - ''
      - '&9Full Expirado: &e%Time%'
      - '&7-------------------------'
    Bidding: #Lore on Bidding Items.
      - '&7-------------------------'
      - '&aClique aqui para penhorar.'
      - ''
      - '&9Vendedor: &e%Seller%'
      - '&9Lance atual: &e$%TopBid%'
      - '&9Ofertador: &e%TopBidder%'
      - '&9Tempo restante: &e%Time%'
      - '&7-------------------------'
    Category-Settings:
      Armor:
        Item: '315'
        Toggle: true
        Slot: 11
        Name: '&6&lArmor'
        Lore:
          - '&7Categoria de armadura.'
      Weapons:
        Item: '283'
        Toggle: true
        Slot: 12
        Name: '&6&lWeapons'
        Lore:
          - '&7Categoria das armas.'
      Tools:
        Item: '285'
        Toggle: true
        Slot: 13
        Name: '&6&lTools'
        Lore:
          - '&7Categoria de ferramentas.'
      Food:
        Item: '322'
        Toggle: true
        Slot: 14
        Name: '&6&lFood'
        Lore:
          - '&7Categoria de comida.'
      Potions:
        Item: '373:8227'
        Toggle: true
        Slot: 15
        Name: '&6&lPotions'
        Lore:
          - '&7Categoria de poções.'
      Blocks:
        Item: '2'
        Toggle: true
        Slot: 16
        Name: '&6&lBlocks'
        Lore:
          - '&7Categoria de blocos.'
      Other:
        Item: '371'
        Toggle: true
        Slot: 17
        Name: '&6&lOthers'
        Lore:
          - '&7Itens de outras categorias.'
      None:
        Item: '166'
        Toggle: true
        Slot: 23
        Name: '&6&lNone'
        Lore:
          - '&7Todas as categorias.'
    OtherSettings: #Other Settings for the GUIs.
      SellingItems: #The button for your current items.
        Item: '264' #The item that this button is.
        Toggle: true #If the item is in the gui or not.
        Slot: 46 #The slot it is in. I recommend not changing these. If you do make sure they are still in the bottom row.
        Name: '&6Itens que quero vender.' #Name of the item.
        Lore: #Lore of the item.
          - '&aClique e veja todos os seus itens.'
      Cancelled/ExpiredItems: #The button for Cancelled/Expired Items.
        Item: '394'
        Toggle: true
        Slot: 47
        Name: '&6Colete os itens aqui.'
        Lore:
          - '&aClique aqui e veja os itens vencidos'
          - '&ae/ou cancelados.'
      PreviousPage: #The button for Previous Page.
        Item: '339'
        Toggle: true
        Slot: 49
        Name: '&6Anterior'
        Lore: {}
      Refesh: #The button for Refresh Page.
        Item: '175'
        Toggle: true
        Slot: 50
        Name: '&6Recarregar'
        Lore: {}
      NextPage: #The button for Next Page.
        Item: '339'
        Toggle: true
        Slot: 51
        Name: '&6Próxima'
        Lore: {}
      Category1: #The button for Next Page.
        Item: '54'
        Toggle: true
        Slot: 52
        Name: '&6Categorias'
        Lore:
          - '&bCategoria atual: &6%Category%'
          - '&aVeja todas as categorias aqui.'
      Category2: #The button for Next Page.
        Item: '54'
        Toggle: true
        Slot: 48
        Name: '&6Categories'
        Lore:
          - '&bCategoria atual: &6%Category%'
          - '&aVeja todas as categorias aqui.'
      Bidding/Selling: #Switch between Bidding and Selling.
        Selling:
          Item: '341'
          Toggle: true
          Slot: 53
          Name: '&6Veja o item a ser vendido.'
          Lore:
            - '&7&l(&6&l!&7&l) &7Clique aqui para'
            - '&7ver itens em penhoria.'
        Bidding:
          Item: '378'
          Toggle: true
          Slot: 53
          Name: '&6Veja o item a ser penhorado.'
          Lore:
            - '&7&l(&6&l!&7&l) &7Clique aqui para'
            - '&7ver o item a ser vendido.'
      WhatIsThis: #The info on all the Books buttons.
        SellingShop: #The Book in the main shop.
          Item: '340'
          Toggle: true
          Slot: 54
          Name: '&6Para que serve isso?'
          Lore:
            - '&aUse para vender seus itens sem loja.'
        BiddingShop: #The Book in the main shop.
          Item: '340'
          Toggle: true
          Slot: 54
          Name: '&6Para que serve isso?'
          Lore:
            - '&aColoque seus itens em leilão/penhora.'
        CurrentItems: #The Book in the Current items GUI.
          Item: '340'
          Toggle: true
          Slot: 54
          Name: '&6Para que serve isso?'
          Lore:
            - '&aSeus itens atuais.'
        Cancelled/ExpiredItems: #The Book in the Cancelled/Expired Items GUI.
          Item: '340'
          Toggle: true
          Slot: 54
          Name: '&6Para que serve isso?'
          Lore:
            - '&aVeja seus itens vencidos aqui.'
        Viewing: #The Book in the Viewing Items GUI.
          Item: '340'
          Toggle: true
          Slot: 50
          Name: '&6Para que serve isso?'
          Lore:
            - '&aVeja o andamento de seus itens.'
        Categories: #The Book in the Viewing Items GUI.
          Item: '340'
          Toggle: true
          Slot: 54
          Name: '&6Para que serve isso?'
          Lore:
            - '&aVeja todas as categorias.'
      Back: #The Back Buttons.
        Item: '339'
        Slot: 46
        Name: '&6Back'
      Return: #The Return Buttons.
        Item: '390'
        Slot: 50
        Name: '&6Voltar tudo.'
        Lore:
          - '&aClique e retorne.'
      Confirm: #The Confirm Buttons.
        Item: '160:5'
        Name: '&aConfirmar'
      Cancel: #The Cancel Buttons.
        Item: '160:14'
        Name: '&cCancelar'
      Your-Item: #The item that shows when you try to buy/bid on your item.
        Item: '166'
        Name: '&cNão pode comprar este item.'
      Cant-Afford: #The item that shows when you cant afford this item.
        Item: '166'
        Name: '&cNão pode ofertar este item.'
      Top-Bidder: #The item for when a player is already the top bidder.
        Item: '166'
        Name: '&cJá é o maior ofertador.'
      Bidding: #The item in the middle when bidding on an item.
        Item: '160:15'
        Name: '&7Leilão'
        Lore:
          - '&7<--&aAdd &cRemove&7-->'
          - '&9Seu lance atual: &e$%Bid%'
          - '&9Ofertador: &e$%TopBid%'
      Bid: #The button for when you want to confirm your bid.
        Item: '160:3'
        Name: '&bDar lance.'
        Lore:
          - '&7Dê seu lance.'
  BlackList:
    - '7'
    - '120'
