EnableAutoUpdater: true
PluginAutoUpdate: 3600
TabAutoUpdate: 5
TagAutoUpdate: 10
Header:
  text: \n&9&l» &6&lAtosMC &9&l« \n      &bSua atitude que faz o jogo!\n
  use: true
Footer:
  text: '\n&DNosso ip: &7play.atosmc.com\n&dNosso site: &7www.atosmc.com\n\n&2Players:
    %online%/%max_online%\n'
  use: true
HideGM3: false
Join:
  Title:
    text: '&5Welcome to'
    subtext: '&5A Minecraft Server!'
    fadein: 5
    stay: 20
    fadeout: 5
    use: false
  Actionbar:
    text: '&5Have fun!'
    use: false
RandomColors:
- '&0'
- '&1'
- '&2'
- '&3'
- '&4'
- '&5'
- '&6'
- '&7'
- '&8'
- '&9'
- '&a'
- '&b'
- '&c'
- '&d'
- '&e'
- '&f'
UseExternalScoreboard: false
ConfigVersion: 3.0.0-pre5
