Enable-Debug: false
Default:
  Difficulty: NORMAL
  PvP-On-Message: '&4Já é de noite!, o PVP foi ativado! ({difficulty})'
  PvP-Off-Message: '&aO sol apareceu!,o PVP foi desativado ({difficulty})'
worlds:
  world:
    Enabled: true
    Only-Difficulty: false
    PvP-On:
      Message: '&4Já é de noite!, o PVP foi ativado! ({difficulty})'
      Difficulty: HARD
      Time: 13000
      Sound: AMBIENT_CAVE
      Commands: []
    PvP-Off:
      Message: '&aO sol apareceu!,o PVP foi desativado ({difficulty})'
      Difficulty: NORMAL
      Time: 0
      Sound: ENTITY_CHICKEN_HURT
      Commands: []
  world_nether:
    Enabled: true
    Only-Difficulty: false
    PvP-On:
      Message: '&4Já é de noite!, o PVP foi ativado! ({difficulty})'
      Difficulty: HARD
      Time: 13000
      Sound: AMBIENT_CAVE
      Commands: []
    PvP-Off:
      Message: '&aO sol apareceu!,o PVP foi desativado ({difficulty})'
      Difficulty: NORMAL
      Time: 0
      Sound: ENTITY_CHICKEN_HURT
      Commands: []
  world_the_end:
    Enabled: true
    Only-Difficulty: false
    PvP-On:
      Message: '&4Já é de noite!, o PVP foi ativado! ({difficulty})'
      Difficulty: HARD
      Time: 13000
      Sound: AMBIENT_CAVE
      Commands: []
    PvP-Off:
      Message: '&aO sol apareceu!,o PVP foi desativado ({difficulty})'
      Difficulty: NORMAL
      Time: 0
      Sound: ENTITY_CHICKEN_HURT
      Commands: []
  Oficial:
    Enabled: true
    Only-Difficulty: false
    PvP-On:
      Message: '&4Já é de noite!, o PVP foi ativado! ({difficulty})'
      Difficulty: HARD
      Time: 13000
      Sound: AMBIENT_CAVE
      Commands: []
    PvP-Off:
      Message: '&aO sol apareceu!,o PVP foi desativado ({difficulty})'
      Difficulty: NORMAL
      Time: 0
      Sound: ENTITY_CHICKEN_HURT
      Commands: []
