Enable-Debug: false
Default:
  Difficulty: NORMAL
  PvP-On-Message: '&4Pvp ativado! Dificuldade {difficulty}'
  PvP-Off-Message: '&aPvp desativado! Dificuldade {difficulty}'
worlds:
  Oficial:
    Enabled: false
    Only-Difficulty: false
    PvP-On:
      Message: '&4It''s Night! PvP is enabled! ({difficulty})'
      Difficulty: HARD
      Time: 13000
      Sound: AMBIENT_CAVE
      Commands: []
    PvP-Off:
      Message: '&aThe sun rises! PvP is off! ({difficulty})'
      Difficulty: NORMAL
      Time: 0
      Sound: ENTITY_CHICKEN_HURT
      Commands: []
  Survival:
    Enabled: true
    Only-Difficulty: false
    PvP-On:
      Message: '&4Pvp ativado! Dificuldade {difficulty}'
      Difficulty: HARD
      Time: 13000
      Sound: AMBIENT_CAVE
      Commands: []
    PvP-Off:
      PvP-Off-Message: '&aPvp desativado! Dificuldade {difficulty}'
      Difficulty: NORMAL
      Time: 0
      Sound: ENTITY_CHICKEN_HURT
      Commands: []
  Mineraￃￃo:
    Enabled: false
    Only-Difficulty: false
    PvP-On:
      Message: '&4Pvp ativado! Dificuldade {difficulty}'
      Difficulty: HARD
      Time: 13000
      Sound: AMBIENT_CAVE
      Commands: []
    PvP-Off:
      Message: '&aThe sun rises! PvP is off! ({difficulty})'
      Difficulty: NORMAL
      Time: 0
      Sound: ENTITY_CHICKEN_HURT
      Commands: []
