# Repeat: Tempo eh em minutos!
#Repeat:
# CMD1:
#    Tempo: 10
#    Comandos:
#    - /meurepeat start
Comandos:
  CMD1:
    Dia: 'Quinta'
    Hora: '21:46'
    Comandos:
    - /kick _Gre pq sim
  CMD2:
    Dia: 'Sabado Domingo'
    Hora: '17:00 18:00'
    Comandos:
    - /meuevento iniciar
