#
# Plugin made by LITEFINE
# Help: https://www.spigotmc.org/resources/litejoin-hidestream-replacing.25771/
Settings:
  PlayerJoinMessage:
    display: true
    displayIfHidden: false
    message: '&8[&2+&8] &e%player% &7entrou no servidor.'
  PlayerQuitMessage:
    display: true
    displayIfHidden: false
    message: '&8[&4-&8] &e%player% &7saiu do servidor.'
  PlayerKickMessage:
    display: falso
    displayIfHidden: false
    message: '&a%player% &fKickado do jogo.'
  ClearInventory:
    enable: false
    needPerms: false
    sendMessage: false
    message: '&a[LJ] &fSeu inventário foi limpo.'
  ResetExperience:
    enable: false
    needPerms: false
    sendMessage: false
    message: '&a[LJ] &fSeu nível de expiração foi limpo.'
  Heal:
    enable: false
    needPerms: false
    sendMessage: false
    message: '&a[LJ] &fVocê foi curado.'
  Feed:
    enable: true
    needPerms: false
    sendMessage: false
    message: '&a[LJ] &fSua fome ficou satisfeita.'
  WelcomeMessage:
    enable: true
    needPerms: false
    message: &8[&2+&8] &e%player% &7entrou no servidor pela primeira vez!
  DonaterJoinMessage:
    display: false
    displayIfHidden: false
    message: '%prefix%%name%&r Entrou no servidor!.'
  TitleWelcome:
    enable: true
    needPerms: false
    firstLine: '&bOlá %player%'
    subLine: Obrigado por entrar em nosso server!
    fadeIn: 20
    stayTime: 50
    fadeOut: 20
  ActionBarWelcome:
    enable: falso
    needPerms: false
    message: Seja Bem Vindo ao Servidor &a%player%
  DamageProtection:
    enable: true
    needPerms: false
    time: 10
    message: '&a[LJ] &fVocê está protegido de danos por 10 segundos'
    endMessage: '&a[LJ] &fProteção acabou.'
  Flight:
    enable: true
    needPerms: true
    justAllowRise: false
    sendMessage: true
    message: '&a[LJ] &fVoo ativo.'
  Glow:
    enable: false
    needPerms: false
    sendMessage: true
    message: '&a[LJ] &fAgora você brilha.'
  Concealment:
    enable: false
    needPerms: true
    sendMessage: true
    message: '&a[LJ] &fVocê estava escondido dos jogadores.'
  JoinEffects:
    enable: false
    removeOldEffects: true
    needPerms: false
    effects:
    - SPEED 1
  JoinParticles:
    enable: false
    needPerms: true
    particle: CRIT
    amount: 40
    offsetX: 0.0
    offsetY: 2.0
    offsetZ: 0.0
  Other:
    enableDeathMessages: false
    spawnTpOnJoin: true
Spawn: {}
