#Placeholders:
#%name% - player's name
#%n% - new line

#Private join message
joinPrivate:
  message: "&eWelcome, &f%name%&e, to the server"
  enable: true
  #In seconds (permission: exgreeting.disable.damage) 
  protectionTime: 5

#Public join message
joinPublic:
  message: "&f%name%&e joined the game"
  enable: true

#Public quit message
quitPublic:
  message: "&f%name%&e left the game"
  enable: true

#Private new player message
newPlayerPrivate:
  message: "&eWelcome, &f%name%&e, to the server!%n%&fGood luck!"
  enable: true
  #If newPlayerPrivate disabled show joinPrivate instead
  usePrivateJoin: false

#Public new player message
newPlayerPublic:
  message: "&f%name%&e new to this server"
  enable: true
  #If newPlayerPublic disabled show joinPublic instead
  usePublicJoin: false